apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  clusterIP: None
  ports:
    - name: mongo
      port: 8081
  selector:
    app: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: locomotive
spec:
  ports:
    - name: locomotive
      port: 3000
  selector:
    app: locomotive
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      imagePullSecrets:
        - name: registry-nextgen
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locomotive
  labels:
    app: locomotive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locomotive
  template:
    metadata:
      labels:
        app: locomotive
    spec:
      containers:
        - name: locomotive
          image: registry.digitalocean.com/nextgen/locomotive
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: production
            - name: RAILS_LOG_TO_STDOUT
              value: enabled
            - name: RAILS_SERVE_STATIC_FILES
              value: enabled
      imagePullSecrets:
        - name: registry-nextgen
