apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  ports:
    - name: proxy
      port: 80
  selector:
    app: proxy
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: registry.digitalocean.com/nextgen/proxy
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: registry-nextgen
