apiVersion: batch/v1
kind: Job
metadata:
  name: solr-reindex
spec:
  template:
    spec:
      containers:
        - name: solr-reindex
          image: registry.digitalocean.com/nextgen/nextgen
          command: ["rails"]
          args: ["sunspot:reindex"]
          env:
            - name: RAILS_ENV
              value: production
      imagePullSecrets:
        - name: registry-nextgen
      restartPolicy: Never
